web/router.ex
defmodule ElixirExperience.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
  end

  pipeline :auth do
    plug ElixirExperience.Plug.CurrentUser
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/" do
    pipe_through [:browser, :auth]

    get "/", ElixirExperience.PageController, :index
    get "/github_oauth", ElixirExperience.GitHubOAuthController, :oauth
    get "/logout", ElixirExperience.GitHubOAuthController, :logout

    resources "/problems", ElixirExperience.ProblemController
  end

  # Other scopes may use custom stacks.
  # scope "/api" do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule ElixirExperience.LayoutView do
  use ElixirExperience.View

  def github_login_url do
    ElixirExperience.GitHubOAuth.authorize_url
  end
end

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Elixir Experience</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/default.min.css">
    <link rel="stylesheet" href="/css/main.css">

    <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-57401852-1', 'auto');
      ga('send', 'pageview');
    </script>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li><a href="/">Home</a></li>
            <%= if @current_user do %>
              <li style="padding: 10px 15px;">
                <img src="<%= @current_user.avatar_url %>" width=30 height=30 />
                <%= @current_user.login %>
              </li>
              <li><a href="<%= git_hub_o_auth_path(@conn, :logout) %>">Logout</a></li>
            <% else %>
              <li><a href="<%= github_login_url %>">Login with GitHub</a></li>
            <% end %>
          </ul>
        </nav>
        <h3>Elixir Experience</h3>
      </div>
      <a class="hidden-xs" href="https://github.com/pgr0ss/elixir_experience"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png"></a>

      <%= @inner %>

    </div> <!-- /container -->
  </body>
</html>