web/router.ex
defmodule ElixirExperience.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
  end

  pipeline :auth do
    plug ElixirExperience.Plug.CurrentUser
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/" do
    pipe_through [:browser, :auth]

    get "/", ElixirExperience.PageController, :index
    get "/github_oauth", ElixirExperience.GitHubOAuthController, :oauth
    get "/logout", ElixirExperience.GitHubOAuthController, :logout

    resources "/problems", ElixirExperience.ProblemController
  end

  # Other scopes may use custom stacks.
  # scope "/api" do
  #   pipe_through :api
  # end
end

web/models/problem.ex
defmodule ElixirExperience.Problem do
  defstruct number: 0, question: "", short_question: "", solution: "", tests: []

  @problems_path "config/problems.exs"

  def load_all do
    [problems: [problems: problems]] = Mix.Config.read!(@problems_path)
    Enum.map(problems, fn problem ->
      %ElixirExperience.Problem{problem |
        short_question: short_question(problem.question),
        question: Earmark.to_html(problem.question)}
    end)
  end

  def display_number(problem) do
    problem.number
    |> Integer.to_string
    |> String.rjust(2, ?0)
  end

  def short_question(question) do
    short_question = question
    |> String.split("\n")
    |> List.first
    |> String.slice(0, 77)

    short_question <> "..."
  end
end

web/controllers/problem_controller.ex
defmodule ElixirExperience.ProblemController do
  use Phoenix.Controller

  plug :action

  def show(conn, %{"id" => id_string}) do
    {id, _} = Integer.parse(id_string)
    render conn, "show.html", problem: ElixirExperience.ProblemList.get_problem(id)
  end

  def update(conn, %{"id" => id_string, "code" => code}) do
    {id, _} = Integer.parse(id_string)
    current_user = conn.assigns[:current_user]
    problem = ElixirExperience.ProblemList.get_problem(id)
    {result, output} = ElixirExperience.CodeRunner.run(code, problem)
    if result == :passed && current_user do
      ElixirExperience.User.create_solution(current_user, problem, code)
    end
    render conn, "results.html", problem: problem, code: code, result: result, output: output
  end
end

web/views/problem_view.ex
defmodule ElixirExperience.ProblemView do
  use ElixirExperience.View

  def show_next_button?(:passed, problem) do
    problem.number < length(ElixirExperience.ProblemList.problems)
  end

  def show_next_button?(_, _) do
    false
  end
end

web/templates/problem/results.html.eex
<h3>
  <%= if @result == :passed do %>
    Correct!
  <% else %>
    Not quite!
  <% end %>
</h3>

<h4>Problem: <%= @problem.number %></h4>

<%= safe @problem.question %>

You submitted:
<pre>
  <code class="elixir"><%= @code %></code>
</pre>

<%= unless @result == :passed do %>
  What went wrong:
  <pre>
    <code class="elixir"><%= @output %></code>
  </pre>
<% end %>

<a href="<%= problem_path(@conn, :show, @problem.number) %>">Back to problem</a>

<%= if show_next_button?(@result, @problem) do %>
  <a class="pull-right" href="<%= problem_path(@conn, :show, @problem.number + 1) %>">Next problem</a>
<% end %>

web/templates/problem/show.html.eex
<h4>Problem: <%= Problem.display_number(@problem) %></h4>

<%= safe @problem.question %>

<%= if User.solved?(@current_user, @problem) do %>
  <h4>Previous solutions</h4>

  <%= Enum.map User.solutions(@current_user, @problem), fn solution -> %>
  <p>Submitted on <%= solution.inserted_at |> Ecto.DateTime.to_date |> Ecto.Date.to_string %>:</p>
  <pre>
    <code class="elixir"><%= solution.code %></code>
  </pre>
  <% end %>
<% end %>

<form action="<%= problem_path(@conn, :update, @problem.number) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <textarea name="code" rows="10" cols="50"></textarea>
  <input type="submit" value="Submit" />
</form>